# Generated by Django 3.0.5 on 2021-05-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_auto_20210508_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('pro_id', models.IntegerField(primary_key=True, serialize=False)),
                ('courseid', models.CharField(max_length=200)),
                ('coursename', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('pro_id', models.IntegerField(primary_key=True, serialize=False)),
                ('institute', models.CharField(max_length=200)),
                ('datefrom', models.DateField()),
                ('dateto', models.DateField()),
                ('major', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='proffesor',
            name='pos',
            field=models.CharField(default='CSE', max_length=50),
        ),
    ]
