# Generated by Django 3.0.5 on 2021-05-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_auto_20210508_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseproff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField()),
                ('courseid', models.CharField(max_length=200)),
                ('coursename', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='educationproff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField()),
                ('institute', models.CharField(max_length=200)),
                ('datefrom', models.DateField()),
                ('dateto', models.DateField()),
                ('major', models.CharField(max_length=200)),
            ],
        ),
    ]
